name: CI/CD .yml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CI/CD
        uses: github/CI/CD@v5

      - name: Build
        run: echo "Add your build steps here"

      - name: Run tests
        run: echo "Add your test commands here"

      - name: Deploy
        run: echo "Add your deployment commands here"

